export const DRUG_CANCEL_LIST_REQUEST = "DRUG_CANCEL_LIST_REQUEST";
export const DRUG_CANCEL_LIST_SUCCESS = "DRUG_CANCEL_LIST_SUCCESS";
export const DRUG_CANCEL_LIST_FAIL = "DRUG_CANCEL_LIST_FAIL";
export const DRUG_CANCEL_LIST_RESET = "DRUG_CANCEL_LIST_RESET";