export const NOTIFICATION_LIST_REQUEST = "NOTIFICATION_LIST_REQUEST";
export const NOTIFICATION_LIST_SUCCESS = "NOTIFICATION_LIST_SUCCESS";
export const NOTIFICATION_LIST_FAIL = "NOTIFICATION_LIST_FAIL";
export const NOTIFICATION_LIST_RESET = "NOTIFICATION_LIST_RESET";

export const NOTIFICATION_SINGLE_REQUEST = "NOTIFICATION_SINGLE_REQUEST";
export const NOTIFICATION_SINGLE_SUCCESS = "NOTIFICATION_SINGLE_SUCCESS";
export const NOTIFICATION_SINGLE_FAIL = "NOTIFICATION_SINGLE_FAIL";
export const NOTIFICATION_SINGLE_RESET = "NOTIFICATION_SINGLE_RESET";

export const NOTIFICATION_UPDATE_REQUEST = "NOTIFICATION_UPDATE_REQUEST";
export const NOTIFICATION_UPDATE_SUCCESS = "NOTIFICATION_UPDATE_SUCCESS";
export const NOTIFICATION_UPDATE_FAIL = "NOTIFICATION_UPDATE_FAIL";
export const NOTIFICATION_UPDATE_RESET = "NOTIFICATION_UPDATE_RESET";

export const NOTIFICATION_SET_OH = "NOTIFICATION_SET_OH";
export const NOTIFICATION_SET_EXP = "NOTIFICATION_SET_EXP";
